version: 3

silent: true

vars:
  PROTO_DIR: ./proto
  PROTO_SERVICE_DIR: ./proto/auth/v1/
  GO_GEN_OUT_DIR: ./gen/go/

tasks:
  generate:
    aliases: ["gen"]
    desc: "Generates code from .proto files."
    cmds:
      - easyp generate
      - go mod tidy